backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'galleria'
    label: 'Gallery'
    widget: 'list'
    optional: true
    fields:
      - { label: 'Title', name: 'imgTitle', widget: 'string' }
      - { label: 'Gallery Image', name: 'imgSrc', widget: 'image' }
      - { label: 'Description', name: 'imgDesc', widget: 'string' }
