backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - label: 'Gallery'
    name: 'galleryImages'
    widget: 'list'
    summary: '{{fields.image}}'
    field: { label: Image, name: image, widget: image }
